{
  "hash": "bbb603a5aa796eee4d80a462af97fcaa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: Sara Cerami\ndate: September 9, 2026\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\nIn this analysis, I look at Median Gross Rent across counties in New York, and\nask which communities we measure most and least reliably.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"NY\"       \nmy_variable <- \"B25064_001\"     \n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 36001 Albany County, New York      B25064_001     1252    22\n2 36003 Allegany County, New York    B25064_001      754    33\n3 36005 Bronx County, New York       B25064_001     1436    11\n4 36007 Broome County, New York      B25064_001      914    26\n5 36009 Cattaraugus County, New York B25064_001      759    30\n6 36011 Cayuga County, New York      B25064_001      895    39\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                        estimate   moe moe_pct\n   <chr>                          <dbl> <dbl>   <dbl>\n 1 Hamilton County, New York        860    95   11.0 \n 2 Schuyler County, New York        858    75    8.74\n 3 Greene County, New York          993    79    7.96\n 4 Lewis County, New York           821    59    7.19\n 5 Orleans County, New York         877    60    6.84\n 6 Yates County, New York           802    46    5.74\n 7 Wyoming County, New York         782    44    5.63\n 8 Cortland County, New York        911    50    5.49\n 9 Chenango County, New York        819    44    5.37\n10 Livingston County, New York      912    48    5.26\n```\n\n\n:::\n:::\n\n\nHamilton County, New York, a rural county Northwest of Albany, has the highest margin of error relative to its estimate. Hamilton County has an 11% margin of error when calculating estimated Median Gross Rent. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    51\n2 Low confidence      1\n3 Moderate           10\n```\n\n\n:::\n:::\n\n\n51 counties in New York fall into the high confidence category, 10 in the moderate confidence category, and 1 in the low confidence category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 36001 Albany County, New York        1252     22  315374    NA\n2 36003 Allegany County, New York       754     33   47027    NA\n3 36005 Bronx County, New York         1436     11 1419250    NA\n4 36007 Broome County, New York         914     26  197738    NA\n5 36009 Cattaraugus County, New York    759     30   76479    NA\n6 36011 Cayuga County, New York         895     39   75464    NA\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         51        381479.\n2 Moderate                11         37898.\n```\n\n\n:::\n:::\n\n\nWith the increased moderate confidence moe_pct threshold from moe_pct < 10 to moe_pct < 15, there are no longer any counties that fall in the low confidence category and instead, counties that fall in the moderate confidence category increase from 10 to 11.\n\nCounties that fall in the high confidence category have an average population of 381,479 while counties that fall in the moderate confidence category have an average population of 37,898. The median population of 381,479 is nearly 10x the population size of the moderate confidence counties (37,898). \n\nWe have the least confident data for smaller, more rural counties. The four least populous counties fall within the moderate confidence category. The remaining 7 counties that fall in the moderate confidence category all fall within the bottom 39th percentile of least populous counties in the state. One reason this could be the case, is that smaller samples provide less confidence given higher rates of variability. Additionally, sparsely populated counties, like Hamilton County (11% moe) and Schuyler County (8.7% moe), require significantly more work for those gathering data. In denser more populous counties like Queens, Kings, and Bronx counties, (all with less than 1% moe), data gathering requires much less travel. Given the higher rate of variability in smaller sample sizes, those in rural, less populous and sparsely populated areas may be inequitably represented by the data. Varying confidence rates allow policy makers to take into account data imprecision. Policy makers or state agencies should not treat data from counties with such divergent population sizes as comparable.  \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}